org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=sequenced_pattern_provider
mod_name=Sequenced Pattern Provider
mod_license=MIT
mod_version=0.3.1
mod_group_id=io.github.createdelight.sequencedpatternprovider
mod_authors=Create Delight Remake
mod_description=One-pattern AE2 automation for Create sequenced assembly lines.

ae2_version_range=[15.4.10,16)
guideme_version_range=[20.1.7,20.2.0)
create_version_range=[6.0.8,6.1)
jade_version_range=[11.13.2,12)
jei_version_range=[15.20.0,16)
